"""Plot palette. GENERATED by scripts/gen_tokens.py from brand/*.yml. Do not edit."""

LIGHT = ("#0072B2", "#D55E00", "#009E73", "#AA3377")
DARK = ("#3F97DB", "#E0702F", "#22AE80", "#A9529E")
NEUTRAL_LIGHT = "#6B7480"
NEUTRAL_DARK = "#8C98A5"
