"""Build notebooks/*.ipynb from labs/src/*.py (jupytext percent format).

One-way and deterministic. The source marks cells with a `role` metadata key:

  ex<N>-head     markdown: intro text placed under the generated exercise heading
  ex<N>-predict  markdown: the Predict prompt
  ex<N>-stub     code:     the # TODO stub (top-level def/class only)
  ex<N>-hint     markdown: the Hint (rendered inside <details>)
  ex<N>-sol      code:     the folded solution (@lab.solution(N) on each def)
  ex<N>-run      code:     the Run cell
  ex<N>-explain  markdown: the Explain prompt
  ex<N>-chk      code:     the checkpoint (lab.check(...))
  stretch        any:      cells of the optional stretch section

Generated cells (excluded from content_sha): the header, the setup cell, the
init cell and the finish cell. Exercise headings come from _variables.yml, so
the site's "In the lab" table and the notebook can never disagree.

Usage:
  uv run python scripts/build_notebooks.py            # build all
  uv run python scripts/build_notebooks.py --check    # fail if any notebook is out of date
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

import jupytext
import nbformat

sys.path.insert(0, str(Path(__file__).resolve().parent))
import variables  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "labs" / "src"
OUT = ROOT / "notebooks"
sys.path.insert(0, str(ROOT / "prl" / "src"))
from prl.record import content_sha  # noqa: E402

ROLE = re.compile(
    r"^ex(?P<n>[0-9]+[a-z]?)-(?P<kind>head|predict|stub|hint|sol|run|explain|chk)(?P<k>[0-9]*)$"
)
CELL_ID = re.compile(r"^[A-Za-z0-9_-]{1,64}$")
INCLUDE = re.compile(r"^#\s*%%\s*include\s+(\S+)\s*$")


class BuildError(Exception):
    pass


# ---------------------------------------------------------------- generated cells
def header_md(mid: str, v: dict[str, Any]) -> str:
    m = v["modules"][mid]
    repo = v["repo"]
    nb_url = f"{repo['colab_base']}/{m['slug']}.ipynb"
    page = f"{repo['site_url']}/modules/{m['slug']}.html"
    if variables.self_paced(m):
        when = f"Pre-work (Module {m['n']}), self-paced · about {m.get('minutes', 20)} min"
    else:
        times = variables.slot_times(m["slot"], v)
        when = (
            f"Day {m['day']} · Module {m['n']} · briefing {times['briefing'][0]}, "
            f"lab {times['lab'][0]}"
        )
    core = variables.core_minutes(m)
    runtime = v["runtimes"][m["runtime"]]["name"]
    objectives = "\n".join(f"- {o}" for o in m["objectives"])
    nxt = _next_module(mid, v)
    next_line = ""
    if nxt:
        nm = v["modules"][nxt]
        next_line = f"\n\n**Next:** [Module {nm['n']} · {nm['title']}]({repo['site_url']}/modules/{nm['slug']}.html)"
    return (
        "<!-- GENERATED by scripts/build_notebooks.py from _variables.yml. Do not edit this cell. -->\n"
        f"# {m['n']} · {m['title']}\n\n"
        f"[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)]({nb_url})\n\n"
        f"**{v['workshop']['title']}** · {when}"
        + ("" if variables.self_paced(m) else f" · core {core} min")
        + f" · designed for {runtime}\n\n"
        f"{m['summary']}\n\n"
        f"**By the end of this notebook you can:**\n\n{objectives}\n\n"
        "**How the lab works.** Each exercise: *Predict* (write your guess first) → a `# TODO` "
        "cell you complete → *Run* → *Explain* → a checkpoint that passes or fails. "
        "A folded Hint and Solution sit under each TODO. The solution never replaces your code; "
        "if you are stuck, run `lab.use_reference(N)` to continue with it.\n\n"
        + (
            f"Read alongside: [the Module {m['n']} page]({page}#in-the-lab)"
            if variables.self_paced(m)
            else f"Briefing: [{page}]({page}#in-the-lab)"
        )
        + next_line
    )


def _next_module(mid: str, v: dict[str, Any]) -> str | None:
    ids = variables.module_ids(v)
    i = ids.index(mid)
    return ids[i + 1] if i + 1 < len(ids) else None


def setup_code(mid: str, pins: dict[str, str], v: dict[str, Any]) -> str:
    allow = sorted(set(v["packages"]["colab"]["allow_upgrade"]) | set(pins))
    pin_lines = ", ".join(f'"{k}": "{val}"' for k, val in pins.items())
    repo = v["repo"]
    return f'''#@title Setup: run this cell first {{ display-mode: "form" }}
# GENERATED by scripts/build_notebooks.py. On Colab it installs exactly what this lab adds
# (keeping every preinstalled package); elsewhere it checks versions and warns.
import importlib.metadata as _md
import os as _os
import subprocess as _sp
import sys as _sys

PRL_REF = "{v["prl"]["ref"]}"  #@param {{type:"string"}}
WORKED = False  #@param {{type:"boolean"}}
SEED = 0  #@param {{type:"integer"}}

_PINS = {{{pin_lines}}}
_ALLOW = {json.dumps(allow)}
_CORE = {json.dumps([n.lower() for n in v["packages"]["colab"]["use_preinstalled"]])}
_PRL_SPEC = _os.environ.get("PRL_SPEC") or "git+{repo["url"]}@" + PRL_REF + "#subdirectory=prl"
_on_colab = ("google.colab" in _sys.modules or bool(_os.environ.get("COLAB_RELEASE_TAG"))
             or _os.environ.get("PRL_PLATFORM") == "colab-sim")


def _norm(name):
    return name.lower().replace("_", "-").replace(".", "-")


def _installed_pins(names=None):
    """One name==version per package: the copy Python imports (first on sys.path).

    Colab's sys.path also holds older system copies of some packages; pinning
    every copy would ask pip for two versions of the same package.
    """
    pins = {{}}
    for d in _md.distributions():
        name = d.metadata["Name"]
        key = _norm(name) if name else None
        if not key or key in pins or key in _keep or (names is not None and key not in names):
            continue
        try:
            pins[key] = f"{{name}}=={{_md.version(name)}}"
        except _md.PackageNotFoundError:
            continue
    return sorted(pins.values())


def _pip_install(constraints):
    with open("/tmp/prl-constraints.txt", "w") as fh:
        fh.write("\\n".join(constraints) + "\\n")
    cmd = [_sys.executable, "-m", "pip", "install", "-q", "-c", "/tmp/prl-constraints.txt",
           *[f"{{k}}=={{val}}" for k, val in _PINS.items()], _PRL_SPEC]
    return _sp.run(cmd, capture_output=True, text=True)


if _on_colab:
    _keep = set(_ALLOW) | {{"prl"}}
    _before = {{k: _md.version(k) for k in ("numpy", "torch", "scipy") if k in _sys.modules}}
    _r = _pip_install(_installed_pins())
    if _r.returncode != 0:
        # Fall back to protecting only the heavy preinstalled packages.
        print("Keeping every preinstalled package was not possible; keeping the core ones "
              f"({{', '.join(_CORE)}}) and retrying.")
        print(_r.stderr.strip().splitlines()[-1] if _r.stderr.strip() else "")
        _r = _pip_install(_installed_pins(set(_CORE)))
    if _r.returncode != 0:
        print(_r.stdout[-3000:], _r.stderr[-3000:])
        raise SystemExit("Setup failed: the runtime's packages changed. Tell the instructor.")
    if any(_md.version(k) != val for k, val in _before.items()):
        print("A package that was already imported changed version: Runtime → Restart session, "
              "then run this cell again.")
else:
    for _name, _want in _PINS.items():
        try:
            _have = _md.version(_name)
        except _md.PackageNotFoundError:
            _have = None
        if _have != _want:
            print(f"Warning: this lab expects {{_name}} {{_want}}, found {{_have}}. "
                  "Run `uv sync --group notebooks` in the repository.")

import prl
import prl.plot
import prl.runtime

prl.runtime.print_versions(extra=list(_PINS))
prl.plot.style()
print(f"SEED = {{SEED}}")'''


def init_code(
    mid: str, sha: str, checkpoints: list[str], pins: dict[str, str], v: dict[str, Any]
) -> str:
    m = v["modules"][mid]
    return (
        "# GENERATED by scripts/build_notebooks.py. Starts the lab harness; rerunning it is safe.\n"
        "import prl.lab\n\n"
        f'lab = prl.lab.init("{m["slug"]}", "{sha}", designed="{m["runtime"]}", '
        f"api={v['prl']['api']}, ns=globals(),\n"
        f"                   checkpoints={json.dumps(checkpoints)}, packages={json.dumps(list(pins))}, "
        "seat=SEED, badge_ref=PRL_REF,\n"
        "                   worked=WORKED or None)"
    )


FINISH_CODE = (
    "# GENERATED by scripts/build_notebooks.py. Prints your summary and your run record.\n"
    "lab.finish()"
)


# ---------------------------------------------------------------- source handling
def read_source(path: Path) -> tuple[str, dict[str, str], list[Any]]:
    text = path.read_text()
    text = _expand_includes(text, path)
    nb = jupytext.reads(text, fmt="py:percent")
    meta = nb.metadata.get("prl", {})
    mid = meta.get("module")
    if not mid:
        raise BuildError(f"{path.name}: front matter needs prl: {{module: mNN}}")
    pins = {str(k): str(val) for k, val in (meta.get("pins") or {}).items()}
    return mid, pins, nb.cells


def _expand_includes(text: str, path: Path) -> str:
    out = []
    for line in text.splitlines():
        m = INCLUDE.match(line)
        if not m:
            out.append(line)
            continue
        inc = ROOT / m.group(1)
        if not inc.is_file():
            raise BuildError(f"{path.name}: include {m.group(1)} not found")
        role = "shared-" + inc.stem.replace("_", "-")
        out.append(f'# %% role="{role}"')
        out.append(f"# Reference code included from {m.group(1)}.")
        out.extend(inc.read_text().rstrip("\n").splitlines())
    return "\n".join(out) + "\n"


def _clean_meta(cell: Any) -> dict[str, Any]:
    keep = {k: val for k, val in cell.metadata.items() if k in {"role", "tags"}}
    return keep


def build(path: Path, v: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    mid, pins, cells = read_source(path)
    if mid not in v["modules"]:
        raise BuildError(f"{path.name}: unknown module {mid}")
    m = v["modules"][mid]
    expected_name = f"{m['slug']}.py"
    if path.name != expected_name:
        raise BuildError(f"{path.name}: must be named {expected_name}")
    ex_meta = {str(e["n"]): e for e in m.get("exercises", [])}

    out_cells: list[nbformat.NotebookNode] = []
    code_for_sha: list[tuple[str, str]] = []
    checkpoints: list[str] = []
    seen_ids: set[str] = set()
    auto = 0
    in_stretch = False

    def add(cell: nbformat.NotebookNode, cid: str, *, hashed: bool) -> None:
        if not CELL_ID.match(cid) or cid in seen_ids:
            raise BuildError(f"{path.name}: bad or duplicate cell id {cid!r}")
        seen_ids.add(cid)
        cell["id"] = cid
        out_cells.append(cell)
        if hashed and cell.cell_type == "code":
            code_for_sha.append((cid, cell.source))

    for cell in cells:
        role = str(cell.metadata.get("role", ""))
        meta = _clean_meta(cell)
        meta.pop("role", None)
        src = cell.source
        if role == "stretch" or role.startswith("stretch"):
            if not in_stretch:
                in_stretch = True
                head = nbformat.v4.new_markdown_cell(
                    "## Stretch (optional) · beyond the core path\n\n"
                    "Nothing later depends on this section."
                )
                add(head, "stretch-head", hashed=False)
        rm = ROLE.match(role)
        if rm:
            n, kind, k = rm.group("n"), rm.group("kind"), rm.group("k")
            if kind == "head":
                if n not in ex_meta:
                    raise BuildError(
                        f"{path.name}: exercise {n} is not in _variables.yml for {mid}"
                    )
                e = ex_meta[n]
                heading = f"## Exercise {n} · {e['title']} ({e['minutes']} min)"
                body = heading + ("\n\n" + src if src.strip() else "")
                add(nbformat.v4.new_markdown_cell(body, metadata=meta), f"ex{n}-head", hashed=False)
                continue
            if kind == "hint":
                body = f"<details><summary>Hint {n}</summary>\n\n{src}\n\n</details>"
                add(nbformat.v4.new_markdown_cell(body, metadata=meta), f"ex{n}-hint", hashed=False)
                continue
            if kind in ("predict", "explain"):
                label = "**Predict.** " if kind == "predict" else "**Explain.** "
                body = src if src.lstrip().startswith("**") else label + src
                add(
                    nbformat.v4.new_markdown_cell(body, metadata=meta),
                    f"ex{n}-{kind}{k}",
                    hashed=False,
                )
                continue
            if cell.cell_type != "code":
                raise BuildError(f"{path.name}: role {role} must be a code cell")
            cid = f"ex{n}-{kind}{k}"
            code_for_sha.append((cid, src))  # hashed before the title is injected
            if kind == "sol":
                names = re.findall(r"^(?:def|class)\s+([A-Za-z_]\w*)", src, re.M)
                title = f'#@title Solution {n} · {", ".join(names) or "reference"} (open after trying) {{ display-mode: "form" }}\n'
                meta = {**meta, "cellView": "form", "jupyter": {"source_hidden": True}}
                src = title + src
            if kind == "chk":
                label = f"{n}.{k}" if k else n
                checkpoints.append(label)
            new = nbformat.v4.new_code_cell(src, metadata=meta)
            new["id"] = cid
            if cid in seen_ids:
                raise BuildError(f"{path.name}: duplicate cell id {cid!r}")
            seen_ids.add(cid)
            out_cells.append(new)
            continue
        # plain cells, includes and stretch cells
        if role == "stretch-sol" and cell.cell_type == "code":
            code_for_sha.append((role, src))
            names = re.findall(r"^(?:def|class)\s+([A-Za-z_]\w*)", src, re.M)
            title = (
                f"#@title Stretch solution · {', '.join(names) or 'reference'} (open after trying) "
                '{ display-mode: "form" }\n'
            )
            new = nbformat.v4.new_code_cell(
                title + src,
                metadata={**meta, "cellView": "form", "jupyter": {"source_hidden": True}},
            )
            new["id"] = role
            seen_ids.add(role)
            out_cells.append(new)
            continue
        if role.startswith("shared-") or role.startswith("stretch"):
            cid = role if role not in seen_ids else f"{role}-{auto}"
        elif role:
            raise BuildError(f"{path.name}: unknown role {role!r}")
        else:
            auto += 1
            cid = f"c{auto:03d}"
        if cell.cell_type == "markdown":
            add(nbformat.v4.new_markdown_cell(src, metadata=meta), cid, hashed=False)
        else:
            add(nbformat.v4.new_code_cell(src, metadata=meta), cid, hashed=True)

    sha = content_sha(code_for_sha)
    head = nbformat.v4.new_markdown_cell(header_md(mid, v))
    head["id"] = "gen-header"
    setup = nbformat.v4.new_code_cell(
        setup_code(mid, pins, v), metadata={"cellView": "form", "tags": ["generated"]}
    )
    setup["id"] = "gen-setup"
    init = nbformat.v4.new_code_cell(
        init_code(mid, sha, checkpoints, pins, v), metadata={"tags": ["generated"]}
    )
    init["id"] = "gen-init"
    finish = nbformat.v4.new_code_cell(FINISH_CODE, metadata={"tags": ["generated"]})
    finish["id"] = "gen-finish"
    head.metadata["tags"] = ["generated"]

    nb = nbformat.v4.new_notebook()
    nb.nbformat, nb.nbformat_minor = 4, 5
    core = [c for c in out_cells if not c["id"].startswith("stretch")]
    stretch = [c for c in out_cells if c["id"].startswith("stretch")]
    # The finish cell comes before the stretch, so an unfinished stretch never blocks the record.
    nb.cells = [head, setup, init, *core, finish, *stretch]
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
        "colab": {"provenance": [], "toc_visible": True},
        "prl": {
            "module": mid,
            "content_sha": sha,
            "source": f"labs/src/{path.name}",
            "checkpoints": checkpoints,
        },
    }
    if v["runtimes"][m["runtime"]].get("gpu"):
        nb.metadata["accelerator"] = "GPU"
        nb.metadata["colab"]["gpuType"] = "T4"
    for cell in nb.cells:
        cell.metadata["id"] = cell["id"]  # Colab deep links (#scrollTo=) use metadata.id
        if cell.cell_type == "code":
            cell.outputs = []
            cell.execution_count = None
    nbformat.validate(nb)
    text = json.dumps(nb, indent=1, sort_keys=True, ensure_ascii=False) + "\n"
    return m["slug"], {"text": text, "nb": nb, "sha": sha, "checkpoints": checkpoints, "mid": mid}


# ---------------------------------------------------------------- lint
def lint(built: dict[str, Any], v: dict[str, Any]) -> list[str]:
    """Rhythm and content rules for one built notebook."""
    p: list[str] = []
    nb, mid = built["nb"], built["mid"]
    m = v["modules"][mid]
    ids = [c["id"] for c in nb.cells]
    exercises = {str(e["n"]): e for e in m.get("exercises", [])}
    present = sorted(
        {re.match(r"ex([0-9]+[a-z]?)-", i).group(1) for i in ids if re.match(r"ex[0-9]", i)},
        key=lambda s: (int(re.match(r"\d+", s).group()), s),
    )
    if m["status"]["lab"] != "stub":
        missing = [n for n in exercises if n not in present]
        if missing:
            p.append(f"{m['slug']}: exercises in _variables.yml but not in the notebook: {missing}")
    for n in present:
        if n not in exercises:
            p.append(f"{m['slug']}: exercise {n} is not listed in _variables.yml")
            continue
        roles = [i.split("-", 1)[1] for i in ids if i.startswith(f"ex{n}-")]
        kinds = [re.sub(r"\d+$", "", r) for r in roles]
        is_reconnect = m["slot"] == "B" and n == "0"
        if is_reconnect:
            continue
        required = ["head", "predict", "run", "explain", "chk"]
        if exercises[n]["writes"]:
            required = ["head", "predict", "stub", "sol", "run", "explain", "chk"]
        for r in required:
            if r not in kinds:
                p.append(f"{m['slug']} exercise {n}: missing a {r} cell")
        order = [k for k in kinds if k in required]
        dedup = [k for i, k in enumerate(order) if i == 0 or order[i - 1] != k]
        if dedup != [r for r in required if r in dedup]:
            p.append(f"{m['slug']} exercise {n}: cells out of order {dedup}; want {required}")
        for cell in nb.cells:
            if cell["id"] == f"ex{n}-stub":
                for line in cell.source.splitlines():
                    if line and not line.startswith((" ", "\t", "#", "def ", "class ", "@", ")")):
                        p.append(
                            f"{m['slug']} exercise {n}: stubs may only define top-level functions/classes"
                        )
                        break
            if (
                cell["id"] == f"ex{n}-stub"
                and "NotImplementedError" in cell.source
                and not re.search(rf"lab\.use_reference\(['\"]?{n}['\"]?[,)]", cell.source)
            ):
                p.append(
                    f"{m['slug']} exercise {n}: the stub's error must name lab.use_reference({n}), "
                    "the way out for a stuck participant"
                )
            if cell["id"] == f"ex{n}-sol" and not re.search(
                rf"@lab\.solution\(['\"]?{n}['\"]?\)", cell.source
            ):
                p.append(f"{m['slug']} exercise {n}: solution must use @lab.solution({n})")
            if cell["id"].startswith(f"ex{n}-chk") and "lab.check(" not in cell.source:
                p.append(f"{m['slug']} exercise {n}: checkpoint must call lab.check(...)")
        # PLAN §3.1: the Predict's answer goes on the pace sheet, and the Explain cites an
        # equation name or a Gotcha of the briefing. A module whose briefing is still a
        # placeholder (M0, pre-work) has nothing to cite yet.
        if m["status"]["briefing"] != "placeholder":
            e = exercises[n]
            if not str(e.get("predict_answer", "")).strip():
                p.append(f"{m['slug']} exercise {n}: _variables.yml needs a predict_answer")
            ref = str(e.get("explain_ref", "")).strip()
            explain = " ".join(
                " ".join(c.source.split()) for c in nb.cells if c["id"] == f"ex{n}-explain"
            )
            if not ref:
                p.append(f"{m['slug']} exercise {n}: _variables.yml needs an explain_ref")
            elif " ".join(ref.split()) not in explain:
                p.append(
                    f"{m['slug']} exercise {n}: the Explain does not cite its explain_ref {ref!r}"
                )
    for cell in nb.cells:
        if cell.cell_type == "markdown" and "generated" not in cell.metadata.get("tags", []):
            if re.search(r"@eq-|^:::|\{\{<", cell.source, re.M):
                p.append(f"{m['slug']} cell {cell['id']}: Quarto syntax in notebook markdown")
            if re.search(r"style=|<font", cell.source):
                p.append(f"{m['slug']} cell {cell['id']}: inline HTML styling in notebook markdown")
    return p


def build_all(check: bool = False) -> int:
    v = variables.load()
    OUT.mkdir(exist_ok=True)
    problems: list[str] = []
    stale: list[str] = []
    built_slugs = []
    for path in sorted(SRC.glob("*.py")):
        try:
            slug, built = build(path, v)
        except BuildError as exc:
            problems.append(str(exc))
            continue
        problems += lint(built, v)
        built_slugs.append(slug)
        target = OUT / f"{slug}.ipynb"
        if check:
            if not target.exists() or target.read_text() != built["text"]:
                stale.append(target.name)
        else:
            target.write_text(built["text"])
    for nb_path in sorted(OUT.glob("*.ipynb")):
        if nb_path.stem not in built_slugs:
            problems.append(f"{nb_path.name} has no source in labs/src/")
    for prob in problems:
        print(f"build_notebooks: {prob}")
    if stale:
        print(f"Out of date: {', '.join(stale)}. Run scripts/build_notebooks.py.")
    if not check and not problems:
        print(f"built {len(built_slugs)} notebook(s)")
    return 1 if problems or stale else 0


if __name__ == "__main__":
    raise SystemExit(build_all(check="--check" in sys.argv[1:]))
