"""Generate the readiness page includes from runs/*.json and _variables.yml.

Writes _includes/readiness.md (verdict, legend, one matrix, details per lab)
and _includes/readiness-summary.md (one sentence for the home and teach
pages). The output never reads the clock: dates come from the records, so the
page does not drift from day to day.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import variables  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
RUNS = ROOT / "runs"
NOTEBOOKS = ROOT / "notebooks"
OUT = ROOT / "_includes"
NOTICE = (
    "<!-- GENERATED by scripts/gen_readiness.py from runs/ and _variables.yml. Do not edit. -->\n"
)

CHIP = {
    "teach": '[[✓]{aria-hidden="true"} Teaching-eligible]{.chip .chip-ok}',
    "real": '[[◐]{aria-hidden="true"} Real path elsewhere]{.chip .chip-partial}',
    "ci": '[[●]{aria-hidden="true"} CI]{.chip .chip-none}',
    "stale": '[[⚠]{aria-hidden="true"} Before the notebook last changed]{.chip .chip-stale}',
    "none": '[[○]{aria-hidden="true"} Not run]{.chip .chip-none}',
    "fail": '[[✗]{aria-hidden="true"} Failed]{.chip .chip-stale}',
}


def load_records() -> list[dict[str, Any]]:
    recs = []
    for p in sorted(RUNS.glob("*.json")):
        rec = json.loads(p.read_text())
        rec["_file"] = p.name
        recs.append(rec)
    return recs


def current_shas() -> dict[str, str]:
    out = {}
    for p in sorted(NOTEBOOKS.glob("*.ipynb")):
        meta = json.loads(p.read_text()).get("metadata", {}).get("prl", {})
        if "content_sha" in meta:
            out[p.stem] = meta["content_sha"]
    return out


def classify(rec: dict[str, Any], mod: dict[str, Any], sha: str | None, prl_version: str) -> str:
    current = (
        sha is not None and rec.get("content_sha") == sha and rec.get("prl_version") == prl_version
    )
    if rec.get("status") != "pass":
        return "fail"
    if not current:
        return "stale"
    clean = (
        (not rec.get("test_doubles"))
        and rec.get("solutions_bound")
        and rec.get("scope") == "notebook"
    )
    if rec.get("env") in ("ci", "ci-proxy") or rec.get("platform") == "ci":
        return "ci"
    if clean and not rec.get("quick") and rec.get("env") == mod["runtime"]:
        return "teach"
    if clean:
        return "real"
    return "ci"


def describe(rec: dict[str, Any]) -> str:
    bits = [rec["date"], rec["env"], f"{rec['seconds']:.0f} s"]
    hw = rec.get("hardware", {})
    if hw.get("gpu"):
        bits.append(hw["gpu"])
    if rec.get("quick"):
        bits.append("QUICK")
    if rec.get("test_doubles"):
        bits.append("test doubles")
    if rec.get("shims"):
        bits.append("shims: " + ", ".join(s["name"] for s in rec["shims"]))
    return " · ".join(bits)


def build(v: dict[str, Any] | None = None) -> tuple[str, str]:
    v = v or variables.load()
    recs = load_records()
    shas = current_shas()
    prl_version = v["prl"]["version"]
    rows, details = [], []
    n_teach = n_any = 0
    total = 0
    for mid in variables.module_ids(v):
        m = v["modules"][mid]
        if not m.get("exercises") and mid != "m15":
            continue
        total += 1
        slug = m["slug"]
        mine = sorted(
            (r for r in recs if r.get("notebook") == slug), key=lambda r: r["date"], reverse=True
        )
        by_class: dict[str, dict[str, Any]] = {}
        for r in mine:
            by_class.setdefault(classify(r, m, shas.get(slug), prl_version), r)
        teach = by_class.get("teach")
        real = by_class.get("real")
        ci = by_class.get("ci")
        stale = by_class.get("stale")
        n_teach += teach is not None
        n_any += bool(mine)
        designed = v["runtimes"][m["runtime"]]["name"]

        def cell(kind: str, rec: dict | None) -> str:
            return f"{CHIP[kind]} {rec['date']}" if rec else "—"

        verdict = "Yes" if teach else "Not yet"
        notes = []
        if stale and not (teach or real):
            notes.append(f"{CHIP['stale']} newest {stale['date']}")
        if "fail" in by_class:
            notes.append(f"{CHIP['fail']} {by_class['fail']['date']}")
        if not mine:
            notes.append(CHIP["none"])
        status = m["status"]["lab"]
        if status in ("planned", "stub"):
            notes.append(f"lab {status}")
        rows.append(
            f"| [{m['n']} · {m['title']}](/modules/{slug}.qmd) | {verdict} | {designed} | "
            f"{cell('teach', teach)} | {cell('real', real)} | {cell('ci', ci)} | {'; '.join(notes) or '—'} |"
        )
        if mine:
            items = "\n".join(
                f"- `{r['_file']}`: {describe(r)} · {CHIP[classify(r, m, shas.get(slug), prl_version)]}"
                for r in mine
            )
            details.append(
                f'::: {{.callout-note collapse="true" title="{m["n"]} · {m["title"]}: {len(mine)} record(s)"}}\n{items}\n:::\n'
            )
    newest = max((r["date"] for r in recs), default=None)
    as_of = f"As of {newest}" if newest else "No run records yet"
    summary = (
        f"**{as_of}: {n_teach} of {total} labs have a teaching-eligible run** (on their designed "
        f"runtime, with their current code). {n_any} of {total} have any run record. "
        "A laptop or CI run shows that code runs; only a recorded run on the designed runtime "
        "counts as ready to teach."
    )
    items = []
    for _rid, item in v["readiness"]["items"].items():
        chk = item["check"]
        if "record" in chk:
            want = chk["record"]
            done = any(
                all(r.get(k) == val for k, val in want.items()) and r.get("status") == "pass"
                for r in recs
            )
        else:
            done = bool(chk.get("done"))
        mark = (
            CHIP["teach"].replace("Teaching-eligible", "Done")
            if done
            else CHIP["none"].replace("Not run", "Open")
        )
        items.append(f"| {item['title']} | {mark} |")
    legend = "\n".join(
        f"- {CHIP[k]}: {text}"
        for k, text in [
            (
                "teach",
                "a passing run on the lab's designed runtime, with current code, full settings, no test doubles.",
            ),
            (
                "real",
                "a passing run of the real path somewhere else (a laptop, AWS), or with QUICK settings.",
            ),
            ("ci", "a CI run: proves the code executes; may use QUICK settings or test doubles."),
            ("stale", "the newest run used an older version of the notebook or of prl."),
            ("none", "no record yet."),
        ]
    )
    page = (
        NOTICE
        + summary
        + "\n\n"
        + "## How to read this page\n\n"
        + legend
        + "\n\n"
        + "## Labs\n\n"
        + "::: {.table-scroll .readiness-matrix}\n"
        + "| Lab | Teach on Colab? | Designed for | On its designed runtime | Real path elsewhere | CI | Notes |\n"
        + "|---|---|---|---|---|---|---|\n"
        + "\n".join(rows)
        + "\n:::\n\n"
        + "## Release items\n\n| Item | Status |\n|---|---|\n"
        + "\n".join(items)
        + "\n\n"
        + ("## Records by lab\n\n" + "\n".join(details) if details else "")
    )
    return page, NOTICE + summary + "\n"


def main(argv: list[str]) -> int:
    page, summary = build()
    targets = {OUT / "readiness.md": page, OUT / "readiness-summary.md": summary}
    if "--check" in argv:
        stale = [p.name for p, t in targets.items() if not p.exists() or p.read_text() != t]
        if stale:
            print(f"Out of date: {', '.join(stale)}. Run scripts/gen_readiness.py.")
            return 1
        return 0
    OUT.mkdir(exist_ok=True)
    for p, t in targets.items():
        p.write_text(t)
    print("wrote _includes/readiness.md, _includes/readiness-summary.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
