"""Generate the site's includes from _variables.yml (and page front matter).

Writes into _includes/:
  module-NN.md   header strip (when), CTA group, facts box (what), recap,
                 What you will build, Before you start
  lab-NN.md      "In the lab" table (from the module's exercises)
  live-NN.md     Agenda (from the page's `live:` front matter)
  day-N.md       module cards for a day page
  schedule.md    the daily clock and what runs in each slot (two narrow tables)
  notebooks.md   lab cards per day
  path.md        the five days and their modules, for the home page
  sidebar.yml    website.sidebar (metadata file)
Also creates a placeholder page modules/NN-slug.qmd for any module without one.

  uv run python scripts/gen_includes.py           # write
  uv run python scripts/gen_includes.py --check   # fail if anything is out of date
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import variables  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
INC = ROOT / "_includes"
MODULES = ROOT / "modules"
NOTICE = "<!-- GENERATED by scripts/gen_includes.py from _variables.yml. Do not edit by hand. -->\n"
NOTICE_YML = "# GENERATED by scripts/gen_includes.py from _variables.yml. Do not edit by hand.\n"


def nn(m: dict[str, Any]) -> str:
    return f"{m['n']:02d}"


def colab_url(m: dict[str, Any], v: dict[str, Any]) -> str:
    return f"{v['repo']['colab_base']}/{m['slug']}.ipynb"


def download_url(m: dict[str, Any], v: dict[str, Any]) -> str:
    return f"{v['repo']['raw_base']}/{m['slug']}.ipynb"


def has_notebook(m: dict[str, Any]) -> bool:
    return (ROOT / "notebooks" / f"{m['slug']}.ipynb").exists()


def page_href(m: dict[str, Any]) -> str:
    return f"/modules/{m['slug']}.qmd"


def duration(m: dict[str, Any], v: dict[str, Any]) -> str:
    if m["day"] == 0:
        return f"{m.get('minutes', 20)} min, before Day 1"
    if m["n"] == 15:
        parts = " · ".join(f"{k} {mins}" for k, mins in v["clock"]["capstone_parts"])
        return f"120 min: {parts}"
    return "120 min: briefing 40 · lab 70 · debrief 10"


def clock_line(m: dict[str, Any], v: dict[str, Any]) -> str:
    if m["day"] == 0:
        return "Pre-work"
    if m["n"] == 15:
        t = variables.capstone_times(v)
        return " · ".join(f"{k.capitalize()} {s}" for k, (s, _) in t.items())
    t = variables.slot_times(m["slot"], v)
    lunch = " · lunch" if m["slot"] == "B" else ""
    return f"Briefing {t['briefing'][0]}{lunch} · Lab {t['lab'][0]} · Debrief {t['debrief'][0]}"


def day_title(m: dict[str, Any], v: dict[str, Any]) -> str:
    if m["day"] == 0:
        return "Before Day 1"
    return f"Day {m['day']} · {v['days'][f'd{m["day"]}']['title']}"


def previous(mid: str, v: dict[str, Any]) -> dict[str, Any] | None:
    ids = variables.module_ids(v)
    i = ids.index(mid)
    return v["modules"][ids[i - 1]] if i > 0 else None


# ---------------------------------------------------------------- module header
def module_md(mid: str, v: dict[str, Any]) -> str:
    m = v["modules"][mid]
    runtime = v["runtimes"][m["runtime"]]["name"]
    level = f"{m['level']} · {v['levels'][m['level']]}"
    core = variables.core_minutes(m)
    live = v["clock"]["budgets"]["live_compute_max"]
    lab_runtime = (
        (
            f"{runtime} · core {core} of 70 min · at most {live} min of live compute "
            "[estimate]{.chip .chip-none}"
        )
        if m["exercises"]
        else f"{runtime} · per track"
    )
    if m["day"] == 0:
        lab_runtime = f"{runtime} · {m.get('minutes', 20)} min [estimate]{{.chip .chip-none}}"
    day_link = "/prepare.qmd" if m["day"] == 0 else f"/day-{m['day']}.qmd"
    slot = "Pre-work" if m["day"] == 0 else f"Slot {m['slot']}"
    objectives = "\n".join(f"- {o}" for o in m["objectives"])
    prev = previous(mid, v)
    before = []
    if prev is not None and m["n"] > 1:
        before.append(
            f"- [Module {prev['n']} · {prev['title']}]({page_href(prev)}) and its lab: this module "
            "builds on what it left open."
        )
    elif m["n"] == 1:
        before.append(
            "- [Module 0 · Setup and hello RL](/modules/00-setup.qmd) and the "
            "[entry check](/prepare.qmd#entry-check)."
        )
    else:
        before.append(
            "- The [entry check](/prepare.qmd#entry-check), to see which areas to brush up."
        )
    if v["runtimes"][m["runtime"]].get("gpu"):
        before.append(
            "- A Google account, and the Colab runtime set to **T4 GPU** (Runtime → Change runtime type)."
        )
    else:
        before.append(
            "- A Google account (Colab's default CPU runtime is enough), or a local or AWS setup "
            "from [Setup](/setup.qmd)."
        )
    before.append("- No API keys or paid services.")
    title_for_sr = f"Lab {m['n']}: {m['title']}"
    return (
        NOTICE
        + "::: {.module-header}\n"
        + f"[{day_title(m, v)}]({day_link}){{.chip}} [Module {m['n']}]{{.chip}} [{slot}]{{.chip}}\n"
        + f"[{clock_line(m, v)}]{{.module-clock}}\n\n"
        + f"::: {{.module-summary}}\n{m['summary']}\n:::\n\n"
        + "::: {.module-actions}\n"
        + (
            f"[Open [{title_for_sr} ]{{.visually-hidden}}in Colab[ (opens in a new tab)]{{.visually-hidden}}]"
            f'({colab_url(m, v)}){{.btn-colab target="_blank" rel="noopener"}} '
            f"[Download .ipynb]({download_url(m, v)}){{.btn-quiet}} "
            if has_notebook(m)
            else "[Lab notebook not built yet]{.btn-disabled} "
        )
        + "[Other ways to run](/setup.qmd#local){.btn-quiet}\n"
        + ":::\n:::\n\n"
        + "::: {.facts}\n"
        + f"Duration\n:   {duration(m, v)}\n\n"
        + f"Level\n:   [{level}](/index.qmd#levels)\n\n"
        + f"Lab runtime\n:   {lab_runtime}\n\n"
        + f"Cost\n:   {m['cost']}\n\n"
        + f"Without GPU\n:   {m['without_gpu']}\n"
        + ":::\n\n"
        + f"::: {{.recap}}\n**Where we are.** {m['where_we_are']} This module asks one question: "
        f"*{m['question']}*\n:::\n\n"
        + f"## What you will build {{#build}}\n\nIn this module you will:\n\n{objectives}\n\n"
        + "## Before you start {#before}\n\n"
        + "\n".join(before)
        + "\n"
    )


def lab_md(mid: str, v: dict[str, Any]) -> str:
    m = v["modules"][mid]
    ex = m.get("exercises", [])
    if not ex:
        return NOTICE + "## In the lab {#in-the-lab}\n\nSee the track starters below.\n"
    core = variables.core_minutes(m)
    rows = []
    for e in ex:
        anchor = f"ex{e['n']}-head"
        title = e["title"]
        bug = " [Planted bug]{.chip .chip-stale}" if title.lower().startswith("planted bug") else ""
        link = f"[{title}]({colab_url(m, v)}#scrollTo={anchor})" if has_notebook(m) else title
        rows.append(f"| {e['n']} | {link}{bug} | {e['minutes']} |")
    stretch = ""
    if m.get("stretch"):
        stretch = (
            f"\n\n::: {{.challenge}}\n**Stretch (optional).** {m['stretch']}. "
            "For anyone who finishes early; nothing later depends on it.\n:::"
        )
    return (
        NOTICE
        + "## In the lab {#in-the-lab}\n\n"
        + "Each exercise you write is a `# TODO` cell with a folded Hint and Solution beneath it and a "
        "checkpoint that passes or fails. Minutes include predicting and explaining.\n\n"
        + "::: {.lab-steps}\n"
        + "| # | Exercise | Min |\n|---|---|---|\n"
        + "\n".join(rows)
        + f"\n| | **Core** | **{core} of 70** |\n:::"
        + stretch
        + "\n"
    )


# ---------------------------------------------------------------- agenda
FRONT = re.compile(r"^---\n(.*?)\n---\n", re.S)


def page_front_matter(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    m = FRONT.match(path.read_text())
    return yaml.safe_load(m.group(1)) or {} if m else {}


def page_sections(path: Path) -> dict[int, str]:
    text = path.read_text() if path.exists() else ""
    return {
        int(n): t.strip() for n, t in re.findall(r"^## (\d+)\. (.+?)(?:\s*\{.*\})?\s*$", text, re.M)
    }


def live_md(mid: str, v: dict[str, Any]) -> str:
    m = v["modules"][mid]
    path = MODULES / f"{m['slug']}.qmd"
    plan = page_front_matter(path).get("live")
    if not plan:
        return (
            NOTICE
            + "::: {.live-plan}\n*The minute-by-minute plan is written with the briefing.*\n:::\n"
        )
    sections = page_sections(path)
    rows, t = [], 0
    expo = act = setup = 0
    for item in plan:
        if "setup" in item:
            mins = int(item["setup"])
            rows.append(f"| {t}–{t + mins} | Setup: open the notebook and run the setup cell | — |")
            setup += mins
            t += mins
            continue
        mins = int(item["minutes"])
        acts = item.get("activities", [])
        a_min = sum(int(a["minutes"]) for a in acts)
        room = (
            "; ".join(
                f"[{a.get('label', a['block'])}](#{a['block']}) ({a['minutes']} min)" for a in acts
            )
            or "—"
        )
        title = sections.get(int(item["section"]), f"Section {item['section']}")
        rows.append(f"| {t}–{t + mins} | {item['section']}. {title} | {room} |")
        expo += mins - a_min
        act += a_min
        t += mins
    extra = f" + {setup} setup" if setup else ""
    return (
        NOTICE
        + "::: {.live-plan}\n| Minutes | Section | In the room |\n|---|---|---|\n"
        + "\n".join(rows)
        + f"\n| **{t}** | **Total** | **{expo} exposition + {act} activities{extra}** |\n"
        + ": Briefing, 40 min {.agenda}\n:::\n"
    )


# ---------------------------------------------------------------- days, schedule, notebooks
def card(m: dict[str, Any], v: dict[str, Any]) -> str:
    runtime = "Colab T4" if v["runtimes"][m["runtime"]].get("gpu") else "Colab CPU"
    core = variables.core_minutes(m)
    core_chip = f" [core {core} min]{{.chip}}" if core else ""
    return (
        f"::: {{.module-card}}\n"
        f"### [{m['n']} · {m['title']}]({page_href(m)})\n\n"
        f"[{clock_line(m, v)}]{{.module-clock}}\n\n"
        f"{m['summary']}\n\n"
        f"[{runtime}]{{.chip}}{core_chip} "
        + (
            f'[Open in Colab]({colab_url(m, v)}){{.btn-quiet target="_blank" rel="noopener"}}'
            if has_notebook(m)
            else "[notebook not built yet]{.chip .chip-none}"
        )
        + "\n:::\n"
    )


def day_md(did: str, v: dict[str, Any]) -> str:
    day = v["days"][did]
    cards = "\n".join(card(v["modules"][mid], v) for mid in day["modules"])
    return NOTICE + f"::: {{.day-cards}}\n{cards}:::\n"


def schedule_md(v: dict[str, Any]) -> str:
    rows = []
    for b in v["clock"]["blocks"]:
        if b["kind"] == "module":
            parts = " · ".join(f"{p} {mins}" for p, mins in b["parts"])
            label = f"Module {b['slot']}: {parts}"
        else:
            label = b["label"] + (" (Day 1 only)" if b.get("days") == [1] else "")
        rows.append(f"| {b['start']}–{b['end']} | {label} |")
    clock = (
        "| Time | Block |\n|---|---|\n"
        + "\n".join(rows)
        + "\n: The daily clock. Every day follows it. {.schedule-clock}\n"
    )
    srows = []
    for _did, day in v["days"].items():
        cells = []
        for mid in day["modules"]:
            m = v["modules"][mid]
            cells.append(f"[{m['n']} · {m['title']}]({page_href(m)})")
        srows.append(f"| [Day {day['n']}](/day-{day['n']}.qmd) | " + " | ".join(cells) + " |")
    slots = (
        "| Day | A · 09:15 | B · 11:30 and 13:10 | C · 14:45 |\n|---|---|---|---|\n"
        + "\n".join(srows)
        + "\n: What runs in each slot. Module B's briefing is before lunch and its lab after. "
        "On Day 5, slot C is the capstone (kickoff 10 · work 80 · share-outs 30). {.schedule-slots}\n"
    )
    return (
        NOTICE
        + "## The daily clock {#clock}\n\n"
        + clock
        + "\n## What runs when {#slots}\n\n"
        + slots
    )


def notebooks_md(v: dict[str, Any]) -> str:
    out = [NOTICE]
    groups = [("Before Day 1", ["m00"])] + [
        (f"Day {d['n']} · {d['title']}", d["modules"]) for d in v["days"].values()
    ]
    for title, mids in groups:
        out.append(f"## {title}\n\n::: {{.lab-list}}\n")
        for mid in mids:
            m = v["modules"][mid]
            runtime = "Colab T4" if v["runtimes"][m["runtime"]].get("gpu") else "Colab CPU"
            out.append(
                f"- **[{m['n']} · {m['title']}]({page_href(m)})** "
                f"[{runtime}]{{.chip}} [lab {m['status']['lab']}]{{.chip}} "
                f"[readiness](/readiness.qmd){{.chip}}  \n"
                + (
                    f'  [Open in Colab]({colab_url(m, v)}){{.btn-quiet target="_blank" rel="noopener"}} '
                    f"[Download]({download_url(m, v)}){{.btn-quiet}}\n"
                    if has_notebook(m)
                    else "  Not built yet.\n"
                )
            )
        out.append(":::\n\n")
    return "".join(out)


def path_md(v: dict[str, Any]) -> str:
    out = [NOTICE, "::: {.path}\n"]
    for _did, day in v["days"].items():
        mods = " → ".join(
            f"[{v['modules'][mid]['title']}]({page_href(v['modules'][mid])})"
            for mid in day["modules"]
        )
        out.append(
            f"**[Day {day['n']} · {day['title']}](/day-{day['n']}.qmd)**  \n"
            f"*{day['question']}*  \n{mods}\n\n"
        )
    out.append(":::\n")
    return "".join(out)


def sidebar_yml(v: dict[str, Any]) -> str:
    m0 = v["modules"]["m00"]
    contents: list[Any] = [{"href": f"modules/{m0['slug']}.qmd", "text": f"0 · {m0['title']}"}]
    for _did, day in v["days"].items():
        contents.append(
            {
                "section": f"Day {day['n']} · {day['title']}",
                "href": f"day-{day['n']}.qmd",
                "contents": [
                    {
                        "href": f"modules/{v['modules'][mid]['slug']}.qmd",
                        "text": f"{v['modules'][mid]['n']} · {v['modules'][mid]['title']}",
                    }
                    for mid in day["modules"]
                ],
            }
        )
    teach = [
        "teach.qmd",
        "facilitator-guide.qmd",
        "instructor-pace.qmd",
        "knowledge-checks.qmd",
        "readiness.qmd",
    ]
    data = {
        "website": {
            "sidebar": [
                {"id": "course", "title": "Course", "style": "docked", "contents": contents},
                {"id": "instructors", "title": "Instructors", "contents": teach},
            ]
        }
    }
    return NOTICE_YML + yaml.safe_dump(data, sort_keys=False, allow_unicode=True)


def placeholder_page(mid: str, v: dict[str, Any]) -> str:
    m = v["modules"][mid]
    return (
        "---\n"
        f'title: "{{{{< var modules.{mid}.title >}}}}"\n'
        "status: placeholder\n"
        "---\n\n"
        f"{{{{< include /_includes/module-{nn(m)}.md >}}}}\n\n"
        f"{{{{< include /_includes/lab-{nn(m)}.md >}}}}\n\n"
        "## Agenda {#agenda}\n\n"
        f"{{{{< include /_includes/live-{nn(m)}.md >}}}}\n\n"
        "::: {.callout-note}\n"
        "This briefing is not written yet. It follows the Module 1 template "
        "(see [the plan](https://github.com/project-delphi/practical-rl/blob/main/PLAN.md)).\n"
        ":::\n"
    )


def outputs(v: dict[str, Any]) -> dict[Path, str]:
    out: dict[Path, str] = {}
    for mid in variables.module_ids(v):
        m = v["modules"][mid]
        out[INC / f"module-{nn(m)}.md"] = module_md(mid, v)
        out[INC / f"lab-{nn(m)}.md"] = lab_md(mid, v)
        out[INC / f"live-{nn(m)}.md"] = live_md(mid, v)
    for did, day in v["days"].items():
        out[INC / f"day-{day['n']}.md"] = day_md(did, v)
    out[INC / "schedule.md"] = schedule_md(v)
    out[INC / "notebooks.md"] = notebooks_md(v)
    out[INC / "path.md"] = path_md(v)
    out[INC / "sidebar.yml"] = sidebar_yml(v)
    return out


def main(argv: list[str]) -> int:
    v = variables.load()
    problems = variables.validate(v)
    if problems:
        for p in problems:
            print(f"_variables.yml: {p}")
        return 1
    check = "--check" in argv
    stale = []
    INC.mkdir(exist_ok=True)
    MODULES.mkdir(exist_ok=True)
    for mid in variables.module_ids(v):
        page = MODULES / f"{v['modules'][mid]['slug']}.qmd"
        if not page.exists():
            if check:
                stale.append(str(page.relative_to(ROOT)))
            else:
                page.write_text(placeholder_page(mid, v))
    for path, text in outputs(v).items():
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(text)
    if stale:
        print("Out of date: " + ", ".join(stale) + ". Run scripts/gen_includes.py.")
        return 1
    if not check:
        print(f"wrote {len(outputs(v))} includes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
