"""Generate prl/src/prl/_palette.py from brand/light.yml and brand/dark.yml.

The site, slides, OJS demos and prl.plot share one palette; the brand files
are the source. Run after editing them (CI's drift gate checks the output).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "prl" / "src" / "prl" / "_palette.py"
HEX = re.compile(r"^#[0-9A-Fa-f]{6}$")


def palette(path: Path) -> dict[str, str]:
    data = yaml.safe_load(path.read_text())
    pal = data["color"]["palette"]
    for name, value in pal.items():
        if not HEX.match(str(value)):
            raise SystemExit(f"{path.name}: palette color {name} = {value!r} is not #RRGGBB")
    return pal


def q(s: str) -> str:
    return '"' + s + '"'


def render() -> str:
    light, dark = palette(ROOT / "brand" / "light.yml"), palette(ROOT / "brand" / "dark.yml")
    series = [f"series-{i}" for i in range(1, 5)]
    lines = [
        '"""Plot palette. GENERATED by scripts/gen_tokens.py from brand/*.yml. Do not edit."""',
        "",
        f"LIGHT = ({', '.join(q(light[s]) for s in series)})",
        f"DARK = ({', '.join(q(dark[s]) for s in series)})",
        f"NEUTRAL_LIGHT = {q(light['neutral'])}",
        f"NEUTRAL_DARK = {q(dark['neutral'])}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is out of date; run scripts/gen_tokens.py")
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
